"""Create .env with generated secrets. Idempotent: never overwrites an existing file."""
import pathlib
import secrets

ENV = pathlib.Path(__file__).resolve().parents[1] / ".env"

if ENV.exists():
    print(f".env already exists, leaving it alone ({ENV})")
    raise SystemExit(0)

ENV.write_text(
    "# Generated by scripts/env_init.py. Never commit this file.\n"
    f"POSTGRES_PASSWORD={secrets.token_urlsafe(24)}\n"
    f"LANGFUSE_NEXTAUTH_SECRET={secrets.token_urlsafe(32)}\n"
    f"LANGFUSE_SALT={secrets.token_urlsafe(32)}\n"
    f"LANGFUSE_ENCRYPTION_KEY={secrets.token_hex(32)}\n"
    "\n# Set when Phase 0.3 adds the OpenRouter provider.\n"
    "OPENROUTER_API_KEY=\n"
    "OLLAMA_BASE_URL=http://localhost:11434/v1\n"
)
print(f"wrote {ENV}")
